import { Poppins } from 'next/font/google'
import { ToastContainer } from 'react-toastify';

import Header from '@/components/Header'
import CustomCursor from '@/components/CustomCursor'

import 'react-toastify/dist/ReactToastify.css';
import './globals.css'

const poppins = Poppins({ subsets: ['latin'], weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'] })

export const metadata = {
  title: 'Eccomerce MGTK',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html className={poppins.className} lang="pt-br">
      <body className='flex flex-col px-2 md:px-10 min-h-screen w-full' >
        <CustomCursor />
        <ToastContainer />

        <Header />
        {children}
      </body>
    </html>
  )
}
